import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Header from '@/components/common/Header';
import MapScene from '@/components/home/MapScene';
import { Info } from '@/types/info';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

type HomeProps = {
  infos: Info[];
};

export default function Home({ infos }: HomeProps) {
  useEffect(() => {
    console.log(infos);
  }, [infos]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MapScene />
    </>
  );
}

// pre-rendering 해서 SSG 생성
export const getStaticProps = async () => {
  const infos = (await import('@/public/data.json')).default;
  return {
    props: { infos },
    // revalidate: 3600,
  };
};
